name: Ma Premiere CI
on: [push]

jobs:
  job_de_test:
    runs-on: ubuntu-latest
    steps:
      - name: Recupere le code
        uses: actions/checkout@v4

      - name: Installe Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Installe Pytest # <--- CETTE Ã‰TAPE EST NOUVELLE
        run: pip install pytest

      - name: Execute mon test de calcul
        run: pytest test_calcul.py

      - name: Installe les dependances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        