name: Pipeline Docker Pro

on: [push]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Recupere le code
        uses: actions/checkout@v4

      - name: Construit l'image Docker
        # Cette étape utilise ton Dockerfile pour tout installer (Python, Pytest, etc.)
        run: docker build -t mon-image-test .

      - name: Execute les tests dans le conteneur
        # Cette étape lance la boîte isolée pour vérifier ton calcul
        run: docker run mon-image-test